
import { Code } from '../types';

const BASE_URI = "http://stratum.app/ontology#";

/**
 * Generates an RDF/XML string representing the Code System as an OWL Ontology.
 */
export const exportOntologyToOwl = (codes: Code[], projectName: string): string => {
  const header = `<?xml version="1.0"?>
<rdf:RDF xmlns="${BASE_URI}"
     xml:base="http://stratum.app/ontology"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:strat="http://stratum.app/schema#">
    
    <owl:Ontology rdf:about="http://stratum.app/ontology">
        <rdfs:comment>Generated by Stratum CAQDAS for project: ${projectName}</rdfs:comment>
        <rdfs:label>Grounded Theory Ontology</rdfs:label>
    </owl:Ontology>
`;

  const classes = codes.map(code => {
    // Determine hierarchy
    const parentResource = code.parentId 
      ? `\n        <rdfs:subClassOf rdf:resource="${BASE_URI}${code.parentId}"/>` 
      : '';
    
    // Custom metadata is stored in strat: namespace or rdfs:comment
    return `
    <owl:Class rdf:about="${BASE_URI}${code.id}">
        <rdfs:label>${escapeXml(code.name)}</rdfs:label>
        <rdfs:comment>${escapeXml(code.description || '')}</rdfs:comment>${parentResource}
        <strat:color>${code.color}</strat:color>
        <strat:kind>${code.kind}</strat:kind>
        <strat:isCore>${code.isCore || false}</strat:isCore>
    </owl:Class>`;
  }).join('');

  return `${header}${classes}\n</rdf:RDF>`;
};

/**
 * Parses an RDF/XML string back into Stratum Code objects.
 */
export const parseOwlToCodes = (text: string): Code[] => {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(text, "text/xml");
  
  // Check for parse errors
  const parseError = xmlDoc.getElementsByTagName("parsererror");
  if (parseError.length > 0) {
      throw new Error("Invalid XML format");
  }

  const classes = xmlDoc.getElementsByTagNameNS("http://www.w3.org/2002/07/owl#", "Class");
  // Fallback if namespace aware parsing fails or for standard tag names
  const allElements = classes.length > 0 ? Array.from(classes) : Array.from(xmlDoc.getElementsByTagName("owl:Class"));

  const codes: Code[] = [];

  allElements.forEach(cls => {
    const about = cls.getAttribute("rdf:about");
    if (!about) return;
    
    // Extract ID from URI (after #)
    const id = about.split('#')[1] || about;
    
    // Helper to get text content of child tag
    const getVal = (tag: string) => {
        const el = cls.getElementsByTagName(tag)[0] || cls.getElementsByTagName("strat:" + tag)[0];
        return el?.textContent || "";
    };

    const label = cls.getElementsByTagName("rdfs:label")[0]?.textContent || "Untitled";
    const description = cls.getElementsByTagName("rdfs:comment")[0]?.textContent || "";
    
    // Stratum specific extensions
    const color = getVal("color") || "#888888";
    const kind = (getVal("kind") as 'code' | 'category') || 'code';
    const isCore = getVal("isCore") === 'true';

    // Hierarchy
    const subClassOf = cls.getElementsByTagName("rdfs:subClassOf")[0];
    let parentId: string | undefined = undefined;
    if (subClassOf) {
        const res = subClassOf.getAttribute("rdf:resource");
        if (res) parentId = res.split('#')[1];
    }

    codes.push({
        id,
        name: label,
        description,
        color,
        kind,
        parentId,
        isCore,
        relatedCodeIds: []
    });
  });

  return codes;
};

const escapeXml = (unsafe: string) => {
    return unsafe.replace(/[<>&'"]/g, (c) => {
        switch (c) {
            case '<': return '&lt;';
            case '>': return '&gt;';
            case '&': return '&amp;';
            case '\'': return '&apos;';
            case '"': return '&quot;';
            default: return c;
        }
    });
}
