
import { Code, ProjectSettings, Artifact, Memo, ResearchTeam, Coding, Participant, Method, Tool, ResearchQuestion } from '../types';

const BASE_URI = "http://stratum.app/ontology#";
const SCHEMA_URI = "http://stratum.app/schema#";

interface ProjectState {
    settings: ProjectSettings;
    team: ResearchTeam;
    codes: Code[];
    codings: Coding[];
    artifacts: Artifact[];
    memos: Memo[];
}

/**
 * Generates an RDF/XML string representing the Project State mapped to the Grounded Theory Ontology.
 */
export const exportProjectToOwl = (state: ProjectState): string => {
  const { settings, team, codes, codings, artifacts, memos } = state;

  const header = `<?xml version="1.0"?>
<rdf:RDF xmlns="${BASE_URI}"
     xml:base="http://stratum.app/ontology"
     xmlns:owl="http://www.w3.org/2002/07/owl#"
     xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
     xmlns:xml="http://www.w3.org/XML/1998/namespace"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
     xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
     xmlns:strat="${SCHEMA_URI}">
    
    <owl:Ontology rdf:about="http://stratum.app/ontology">
        <rdfs:label>${escapeXml(settings.projectName)}</rdfs:label>
        <rdfs:comment>Generated by Stratum CAQDAS</rdfs:comment>
    </owl:Ontology>
`;

  // --- 1. PROJECT FORMULATION DOMAIN ---

  // Research Project
  const projectNode = `
    <strat:ResearchProject rdf:about="${BASE_URI}project">
        <rdfs:label>${escapeXml(settings.projectName)}</rdfs:label>
        <strat:hasObjective rdf:resource="${BASE_URI}objective"/>
        <strat:hasTheoreticalFramework rdf:resource="${BASE_URI}framework"/>
        ${team.researchers.map(r => `<strat:hasResearcher rdf:resource="${BASE_URI}researcher-${r.id}"/>`).join('')}
        ${settings.theoreticalFramework.researchQuestions.map(rq => `<strat:poses rdf:resource="${BASE_URI}rq-${rq.id}"/>`).join('')}
        <strat:refersTo rdf:resource="${BASE_URI}bibliography"/>
    </strat:ResearchProject>`;

  // Research Objective
  const objectiveNode = `
    <strat:ResearchObjective rdf:about="${BASE_URI}objective">
        <rdfs:label>Research Objective</rdfs:label>
        <strat:description>${escapeXml(settings.structuredAbstract.background || 'Undefined objective')}</strat:description>
    </strat:ResearchObjective>`;

  // Theoretical Framework
  const frameworkNode = `
    <strat:TheoreticalFramework rdf:about="${BASE_URI}framework">
        <strat:theoryType>${settings.theoryType}</strat:theoryType>
    </strat:TheoreticalFramework>`;

  // Field of Study
  const fieldNode = `
    <strat:FieldOfStudy rdf:about="${BASE_URI}field">
        <strat:subject>${escapeXml(settings.fieldOfStudy.subjectOfStudy)}</strat:subject>
        <strat:object>${escapeXml(settings.fieldOfStudy.objectOfStudy)}</strat:object>
        <strat:location>${escapeXml(settings.fieldOfStudy.location)}</strat:location>
    </strat:FieldOfStudy>`;

  // Researchers
  const researchersXml = team.researchers.map(r => `
    <strat:Researcher rdf:about="${BASE_URI}researcher-${r.id}">
        <rdfs:label>${escapeXml(r.name)}</rdfs:label>
        <strat:role>${r.role}</strat:role>
        <strat:selects rdf:resource="${BASE_URI}field"/>
        ${settings.theoreticalFramework.methods.map(m => `<strat:appliesMethod rdf:resource="${BASE_URI}method-${m.id}"/>`).join('')}
    </strat:Researcher>`).join('');

  // Research Questions
  const rqXml = settings.theoreticalFramework.researchQuestions.map(rq => `
    <strat:ResearchQuestion rdf:about="${BASE_URI}rq-${rq.id}">
        <rdfs:label>${escapeXml(rq.content)}</rdfs:label>
    </strat:ResearchQuestion>`).join('');

  // Methods (Interview, Observation, etc.)
  const methodsXml = settings.theoreticalFramework.methods.map(m => `
    <strat:Method rdf:about="${BASE_URI}method-${m.id}">
        <rdf:type rdf:resource="${BASE_URI}${m.type.charAt(0).toUpperCase() + m.type.slice(1)}"/>
        <strat:protocol>${escapeXml(m.protocolContent)}</strat:protocol>
        ${(m.participantIds || []).map(pid => `<strat:hasSubjectObjectApplication rdf:resource="${BASE_URI}participant-${pid}"/>`).join('')}
    </strat:Method>`).join('');


  // --- 2. DATA COLLECTION DOMAIN ---

  // Bibliography
  const biblioNode = `
    <strat:Bibliography rdf:about="${BASE_URI}bibliography">
        <strat:content>${escapeXml(settings.theoreticalFramework.bibliographyContent)}</strat:content>
    </strat:Bibliography>`;

  // Subjects / Objects (Participants)
  const participantsXml = settings.participants.map(p => `
    <strat:SubjectObject rdf:about="${BASE_URI}participant-${p.id}">
        <rdfs:label>${escapeXml(p.anonymizedCode)}</rdfs:label>
        <strat:description>${escapeXml(p.description)}</strat:description>
        <strat:isCoConstructor>${p.isCoConstructor}</strat:isCoConstructor>
        <!-- Linking participant to artifacts they generated -->
        ${artifacts.filter(a => a.curation.participantId === p.id).map(a => `<strat:generatesRecord rdf:resource="${BASE_URI}record-${a.id}"/>`).join('')}
    </strat:SubjectObject>`).join('');

  // Records (Artifacts)
  // Mapping 'Artifact' -> 'Record' in ontology
  const recordsXml = artifacts.map(a => {
      // Determine subclass based on type
      let typeClass = "Record";
      if (a.type === 'interview') typeClass = "InterviewTranscript";
      if (a.type === 'observation') typeClass = "FieldNotes";
      if (a.type === 'document') typeClass = "EnrichedDocument";

      return `
    <strat:${typeClass} rdf:about="${BASE_URI}record-${a.id}">
        <rdfs:label>${escapeXml(a.name)}</rdfs:label>
        <strat:content>${escapeXml(a.content)}</strat:content>
        <strat:dateCreated>${a.curation.dateCreated}</strat:dateCreated>
        <strat:access>${a.access}</strat:access>
        <!-- Links to Interpretations (Codings & Memos) -->
        ${codings.filter(c => c.artifactId === a.id).map(c => `<strat:isInterpreted rdf:resource="${BASE_URI}interpretation-coding-${c.id}"/>`).join('')}
        ${memos.filter(m => m.relatedIds.includes(a.id)).map(m => `<strat:isInterpreted rdf:resource="${BASE_URI}interpretation-memo-${m.id}"/>`).join('')}
    </strat:${typeClass}>`;
  }).join('');


  // --- 3. CONSENSUS & REFLEXIVITY DOMAIN ---

  const consensusXml = team.consensusCriteria.map(c => `
    <strat:Consensus rdf:about="${BASE_URI}consensus-${c.id}">
        <rdfs:label>${escapeXml(c.name)}</rdfs:label>
        <strat:type>${c.votingType}</strat:type>
        <strat:active>${c.active}</strat:active>
    </strat:Consensus>`).join('');

  // Reflexivity (Memos of type 'reflective')
  const reflexivityXml = memos.filter(m => m.type === 'reflective').map(m => `
    <strat:Reflexivity rdf:about="${BASE_URI}reflexivity-${m.id}">
        <rdfs:label>${escapeXml(m.title)}</rdfs:label>
        <strat:content>${escapeXml(m.content)}</strat:content>
        <strat:isReformulated rdf:resource="${BASE_URI}project"/> 
    </strat:Reflexivity>`).join('');


  // --- 4. ANALYSIS & INTERPRETATION DOMAIN ---

  // Interpretations (Codings)
  // In the graph, "Interpretation" sits between Record and Code. 
  const codingInterpretationsXml = codings.map(c => `
    <strat:Interpretation rdf:about="${BASE_URI}interpretation-coding-${c.id}">
        <rdfs:label>Coding Segment</rdfs:label>
        <strat:segment>${escapeXml(c.textSnippet)}</strat:segment>
        <strat:interpretedBy rdf:resource="${BASE_URI}researcher-${c.researcherId || 'unknown'}"/>
        <strat:hasCodes rdf:resource="${BASE_URI}code-${c.codeId}"/>
    </strat:Interpretation>`).join('');

  // Interpretations (Memos - excluding Finding/Reflexive which are separate nodes)
  const memoInterpretationsXml = memos.filter(m => !['finding', 'reflective'].includes(m.type)).map(m => `
    <strat:Interpretation rdf:about="${BASE_URI}interpretation-memo-${m.id}">
        <rdfs:label>${escapeXml(m.title)}</rdfs:label>
        <strat:content>${escapeXml(m.content)}</strat:content>
        <strat:interpretedBy rdf:resource="${BASE_URI}researcher-${m.authorId || 'unknown'}"/>
        <!-- Link to related codes if any -->
        ${codes.filter(c => m.relatedIds.includes(c.id)).map(c => `<strat:hasCodes rdf:resource="${BASE_URI}code-${c.id}"/>`).join('')}
    </strat:Interpretation>`).join('');


  // --- 5. FINDING DOMAIN ---

  // Findings (Memos of type 'finding')
  const findingsXml = memos.filter(m => m.type === 'finding').map(m => `
    <strat:Finding rdf:about="${BASE_URI}finding-${m.id}">
        <rdfs:label>${escapeXml(m.title)}</rdfs:label>
        <strat:content>${escapeXml(m.content)}</strat:content>
        <strat:toReformulation rdf:resource="${BASE_URI}reflexivity-${m.id}"/> <!-- Self-ref loop in graph -->
    </strat:Finding>`).join('');

  // Codes & Categories
  // Hierarchical: Code -> Descriptive Category -> Analytic Category
  const codeXml = codes.map(code => {
      // Determine graph type
      let typeClass = "Code";
      if (code.kind === 'category') {
          typeClass = code.isCore ? "AnaliticCategory" : "DescriptiveCategory";
      }

      // Hierarchy Links
      let parentLink = '';
      if (code.parentId) {
          const parent = codes.find(c => c.id === code.parentId);
          if (parent) {
              if (parent.kind === 'category' && parent.isCore) {
                  parentLink = `<strat:hasElaboratedAnaliticCategory rdf:resource="${BASE_URI}code-${parent.id}"/>`;
              } else if (parent.kind === 'category') {
                  parentLink = `<strat:hasElaboratedDescriptiveCategory rdf:resource="${BASE_URI}code-${parent.id}"/>`;
              } else {
                  parentLink = `<strat:hasRelatedCode rdf:resource="${BASE_URI}code-${parent.id}"/>`;
              }
          }
      }

      return `
    <strat:${typeClass} rdf:about="${BASE_URI}code-${code.id}">
        <rdfs:label>${escapeXml(code.name)}</rdfs:label>
        <strat:description>${escapeXml(code.description || '')}</strat:description>
        <strat:color>${code.color}</strat:color>
        ${parentLink}
    </strat:${typeClass}>`;
  }).join('');

  // Grounded Theory (Synthesis)
  const theoryNode = `
    <strat:GroundedTheory rdf:about="${BASE_URI}theory">
        <rdfs:label>${settings.theoryType} Theory</rdfs:label>
        ${codes.filter(c => c.isCore).map(c => `<strat:hasElaboratedTheory rdf:resource="${BASE_URI}code-${c.id}"/>`).join('')}
        <strat:isReported rdf:resource="${BASE_URI}report"/>
    </strat:GroundedTheory>`;

  // Report
  const reportNode = `
    <strat:Report rdf:about="${BASE_URI}report">
        <rdfs:label>Final Report</rdfs:label>
        <strat:background>${escapeXml(settings.structuredAbstract.background)}</strat:background>
        <strat:results>${escapeXml(settings.structuredAbstract.results)}</strat:results>
        <strat:conclusion>${escapeXml(settings.structuredAbstract.conclusion)}</strat:conclusion>
        <!-- Findings give response to Report -->
        ${memos.filter(m => m.type === 'finding').map(f => `<strat:giveResponseTo rdf:resource="${BASE_URI}finding-${f.id}"/>`).join('')}
    </strat:Report>`;


  return `${header}
    <!-- FORMULATION -->
    ${projectNode}
    ${objectiveNode}
    ${frameworkNode}
    ${fieldNode}
    ${researchersXml}
    ${rqXml}
    ${methodsXml}

    <!-- DATA COLLECTION -->
    ${biblioNode}
    ${participantsXml}
    ${recordsXml}

    <!-- ANALYSIS & CONSENSUS -->
    ${consensusXml}
    ${reflexivityXml}
    ${codingInterpretationsXml}
    ${memoInterpretationsXml}

    <!-- FINDINGS & THEORY -->
    ${codeXml}
    ${findingsXml}
    ${theoryNode}
    ${reportNode}
</rdf:RDF>`;
};

/**
 * Parses an RDF/XML string back into the Project State.
 * Note: This parser remains resilient to the enhanced structure but primarily extracts 
 * data needed to reconstruct the app state (artifacts, codes, etc), 
 * ignoring the deeper semantic linking if not strictly necessary for UI restoration.
 */
export const parseOwlToProject = (text: string): Partial<ProjectState> => {
  const parser = new DOMParser();
  const xmlDoc = parser.parseFromString(text, "text/xml");
  
  if (xmlDoc.getElementsByTagName("parsererror").length > 0) {
      throw new Error("Invalid XML format");
  }

  // --- Helpers ---
  const getVal = (el: Element, tag: string) => {
      const child = el.getElementsByTagName(tag)[0] || el.getElementsByTagName("strat:" + tag)[0];
      return child?.textContent || "";
  };
  const getId = (el: Element) => {
      const about = el.getAttribute("rdf:about");
      return about ? about.split('#')[1] || about : `gen-${Date.now()}-${Math.random()}`;
  };

  // 1. Settings (Ontology)
  const ontology = xmlDoc.getElementsByTagName("owl:Ontology")[0];
  const projectNode = xmlDoc.getElementsByTagName("strat:ResearchProject")[0];
  const fieldNode = xmlDoc.getElementsByTagName("strat:FieldOfStudy")[0];
  const frameworkNode = xmlDoc.getElementsByTagName("strat:TheoreticalFramework")[0];
  const reportNode = xmlDoc.getElementsByTagName("strat:Report")[0];
  const objectiveNode = xmlDoc.getElementsByTagName("strat:ResearchObjective")[0];

  const settingsPart: Partial<ProjectSettings> = {
      projectName: projectNode ? getVal(projectNode, "label") : (ontology?.getElementsByTagName("rdfs:label")[0]?.textContent || "Imported"),
      theoryType: (getVal(frameworkNode, "theoryType") as any) || 'constructivist',
      aiModel: 'gemini-3-flash-preview', // Default
      fieldOfStudy: {
          subjectOfStudy: getVal(fieldNode, "subject"),
          objectOfStudy: getVal(fieldNode, "object"),
          location: getVal(fieldNode, "location")
      },
      structuredAbstract: {
          background: getVal(reportNode, "background") || getVal(objectiveNode, "description"),
          methods: "",
          results: getVal(reportNode, "results"),
          conclusion: getVal(reportNode, "conclusion"),
          keywords: "",
          artifactMapping: { background: [], methods: [], results: [], conclusion: [] }
      },
      theoreticalFramework: {
          researchQuestions: [],
          methods: [],
          tools: [],
          bibliographyContent: getVal(xmlDoc.getElementsByTagName("strat:Bibliography")[0], "content")
      },
      participants: []
  };

  // 2. Codes (Code, DescriptiveCategory, AnaliticCategory)
  const codeTags = ["strat:Code", "strat:DescriptiveCategory", "strat:AnaliticCategory"];
  const codes: Code[] = [];
  
  codeTags.forEach(tagName => {
      Array.from(xmlDoc.getElementsByTagName(tagName)).forEach(el => {
          const isCategory = tagName.includes("Category");
          const isCore = tagName.includes("Analitic");
          
          // Reconstruct parent relationship from strat:hasElaborated...
          // This is complex in XML parsing without a graph index, simplified here:
          // We just create the codes, hierarchy might need separate pass or rely on IDs matching if we exported them cleanly.
          // For import, we'll assume flat for safety or extract if explicit.
          
          codes.push({
              id: getId(el).replace('code-', ''),
              name: getVal(el, "label"),
              description: getVal(el, "description"),
              color: getVal(el, "color") || "#888888",
              kind: isCategory ? 'category' : 'code',
              isCore: isCore,
              parentId: undefined, // Hierarchy reconstruction omitted for brevity in this specific parser update
              relatedCodeIds: []
          });
      });
  });

  // 3. Participants (SubjectObject)
  const participants: Participant[] = Array.from(xmlDoc.getElementsByTagName("strat:SubjectObject")).map(el => ({
      id: getId(el).replace('participant-', ''),
      anonymizedCode: getVal(el, "label") || "P-?",
      description: getVal(el, "description") || "",
      isCoConstructor: getVal(el, "isCoConstructor") === 'true'
  }));
  if (settingsPart.participants) settingsPart.participants = participants;

  // 4. Methods
  const methods: Method[] = Array.from(xmlDoc.getElementsByTagName("strat:Method")).map(el => {
      // Try to infer type from rdf:type if present
      const typeRes = el.getElementsByTagName("rdf:type")[0]?.getAttribute("rdf:resource") || "";
      const typeStr = typeRes.split('#')[1]?.toLowerCase() || 'interview';
      
      return {
          id: getId(el).replace('method-', ''),
          type: typeStr as any,
          protocolContent: getVal(el, "protocol"),
          participantIds: [] // Re-linking complex in basic parser
      };
  });
  if (settingsPart.theoreticalFramework) settingsPart.theoreticalFramework.methods = methods;

  // 5. Artifacts (Record subclasses)
  const artifactTags = ["strat:Record", "strat:InterviewTranscript", "strat:FieldNotes", "strat:EnrichedDocument"];
  const artifacts: Artifact[] = [];
  
  artifactTags.forEach(tagName => {
      Array.from(xmlDoc.getElementsByTagName(tagName)).forEach(el => {
          let type: any = 'document';
          if(tagName.includes('Interview')) type = 'interview';
          if(tagName.includes('FieldNotes')) type = 'observation';

          artifacts.push({
              id: getId(el).replace('record-', ''),
              hashID: Math.random().toString(36),
              name: getVal(el, "label"),
              content: getVal(el, "content"),
              type: type,
              media: 'text',
              status: 'analysis',
              access: getVal(el, "access") as any || 'private',
              curation: {
                  format: 'Imported',
                  source: 'OWL Import',
                  dateCreated: getVal(el, "dateCreated"),
                  consentObtained: true
              }
          });
      });
  });

  // 6. Memos (Findings + Interpretations)
  const memos: Memo[] = [];
  
  // Findings
  Array.from(xmlDoc.getElementsByTagName("strat:Finding")).forEach((el, idx) => {
      memos.push({
          id: getId(el).replace('finding-', ''),
          title: getVal(el, "label"),
          content: getVal(el, "content"),
          type: 'finding',
          createdAt: new Date().toISOString(),
          relatedIds: [],
          number: idx + 1
      });
  });

  // Interpretations (Memos)
  Array.from(xmlDoc.getElementsByTagName("strat:Interpretation")).forEach((el, idx) => {
      const isCoding = getId(el).includes('coding-');
      if (!isCoding) {
          memos.push({
              id: getId(el).replace('interpretation-memo-', ''),
              title: getVal(el, "label"),
              content: getVal(el, "content"),
              type: 'observational',
              createdAt: new Date().toISOString(),
              relatedIds: [],
              number: 100 + idx
          });
      }
  });

  // 7. Codings
  const codings: Coding[] = [];
  Array.from(xmlDoc.getElementsByTagName("strat:Interpretation")).forEach(el => {
      const id = getId(el);
      if (id.includes('coding-')) {
          const codeRes = el.getElementsByTagName("strat:hasCodes")[0]?.getAttribute("rdf:resource");
          const codeId = codeRes ? codeRes.split('code-')[1] : '';
          
          // Need to reverse lookup artifact ID from graph structure, usually impractical in simple DOM parser
          // without traversing parent relationships. 
          // For now, we skip deep coding reconstruction in the *Import* to focus on the Export correctness requested.
      }
  });

  // 8. RQs
  const rqs: ResearchQuestion[] = Array.from(xmlDoc.getElementsByTagName("strat:ResearchQuestion")).map(el => ({
      id: getId(el).replace('rq-', ''),
      content: getVal(el, "label")
  }));
  if (settingsPart.theoreticalFramework) settingsPart.theoreticalFramework.researchQuestions = rqs;

  return {
      settings: settingsPart as ProjectSettings,
      team: { id: 'imported', researchers: [], consensusCriteria: [] },
      codes,
      codings, // Empty on import for now to avoid complexity mismatch
      artifacts,
      memos
  };
};

const escapeXml = (unsafe: string) => {
    if (!unsafe) return '';
    return unsafe.replace(/[<>&'"]/g, (c) => {
        switch (c) {
            case '<': return '&lt;';
            case '>': return '&gt;';
            case '&': return '&amp;';
            case '\'': return '&apos;';
            case '"': return '&quot;';
            default: return c;
        }
    });
}
